name: CI-CD for Application
on:
   push:
     branches: [main]
   workflow_dispatch:

jobs:
    build_and_deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Display contents of hell.txt
          uses: actions/checkout@v3
          run: cat hello.txt
