name: CI-CD for Application
on:
   push:
     branches: [main]
   workflow_dispatch:

jobs:
    build_and_deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
        - name: Display contents of hello.txt
          run: cat hello.txt
        - name: ENV check
          env:
            ENV_TEST: ${{ vars.ENV_TEST }}
          run: echo $ENV_TEST
        - name: Secret check
          env:
            SECRET_ENV: ${{ secrets.SECRET_ENV }}
          run: echo $SECRET_ENV
